// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Data.Entity.ModelConfiguration.Conventions;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace AugustCodingExercise
{
    public partial class AugustCodingDBContext : DbContext
    {
        public AugustCodingDBContext()
        {
        }

        public AugustCodingDBContext(DbContextOptions<AugustCodingDBContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Person> Person { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Scaffolding:ConnectionString", "Data Source=(local);Initial Catalog=AugustCodingDB;Integrated Security=true");
            
            modelBuilder.Entity<Person>(entity =>
            {
                entity.Property(e => e.FirstName).HasMaxLength(250);

                entity.Property(e => e.Honorific).HasMaxLength(10);

                entity.Property(e => e.LastName).HasMaxLength(250);

                entity.Property(e => e.MiddleName).HasMaxLength(250);

                entity.Property(e => e.PersonCode).HasMaxLength(10);
            });
            modelBuilder.Entity<Person>().ToTable("Person");
            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}