// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace AugustCodingExercise
{
    public partial class PeopleDBContext : DbContext
    {
        public PeopleDBContext()
        {
        }

        public PeopleDBContext(DbContextOptions<PeopleDBContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Person> Person { get; set; }
        public virtual DbSet<PersonType> PersonType { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Scaffolding:ConnectionString", "Data Source=(local);Initial Catalog=AugustCodingDB;Integrated Security=true");

            modelBuilder.Entity<Person>(entity =>
            {
                entity.HasOne(d => d.PersonCodeNavigation)
                    .WithMany(p => p.Person)
                    .HasForeignKey(d => d.PersonCode)
                    .HasConstraintName("FK_Person_PersonType");
            });

            modelBuilder.Entity<PersonType>(entity =>
            {
                entity.Property(e => e.TypeDescription).IsFixedLength();
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}