// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AugustCodingExercise
{
    public partial class DeductionType
    {
        [Key]
        [StringLength(10)]
        public string DeductionTypeCode { get; set; }
        [StringLength(250)]
        public string TypeDescription { get; set; }
        public bool? AppliesToEmp { get; set; }
        public bool? AppliesToDep { get; set; }
        public bool? AppliesToSpo { get; set; }
        [Column(TypeName = "numeric(18, 2)")]
        public decimal? EmpAmt { get; set; }
        [Column(TypeName = "numeric(18, 2)")]
        public decimal? DepAmt { get; set; }
        [Column(TypeName = "numeric(18, 2)")]
        public decimal? SpoAmt { get; set; }
    }
}