// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AugustCodingExercise
{
    public partial class PayrollRuns
    {
        [Key]
        public long PayrollId { get; set; }
        public long RunId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime WeekEnding { get; set; }
        public long PersonId { get; set; }
        [Required]
        [StringLength(10)]
        public string Status { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CheckDate { get; set; }
        [Column(TypeName = "numeric(18, 2)")]
        public decimal? GrossPay { get; set; }
        [Column(TypeName = "numeric(18, 2)")]
        public decimal? Deduction { get; set; }
        [StringLength(10)]
        public string DeductionType { get; set; }
        [Column(TypeName = "numeric(18, 2)")]
        public decimal? Discount { get; set; }
        [StringLength(10)]
        public string DiscountType { get; set; }
        [Column(TypeName = "numeric(18, 2)")]
        public decimal? NetPay { get; set; }
        public int? Year { get; set; }

        [ForeignKey(nameof(DeductionType))]
        [InverseProperty("PayrollRuns")]
        public virtual DeductionType DeductionTypeNavigation { get; set; }
        [ForeignKey(nameof(DiscountType))]
        [InverseProperty("PayrollRuns")]
        public virtual DiscountType DiscountTypeNavigation { get; set; }
        [ForeignKey(nameof(PersonId))]
        [InverseProperty("PayrollRuns")]
        public virtual Person Person { get; set; }
    }
}