// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AugustCodingExercise
{
    public partial class Person
    {
        [Key]
        public long PersonId { get; set; }
        [StringLength(10)]
        public string PersonCode { get; set; }
        [StringLength(10)]
        public string Honorific { get; set; }
        [StringLength(250)]
        public string FirstName { get; set; }
        [StringLength(250)]
        public string MiddleName { get; set; }
        [StringLength(250)]
        public string LastName { get; set; }
        [Column(TypeName = "numeric(18, 2)")]
        public decimal? Salary { get; set; }

        [ForeignKey(nameof(PersonCode))]
        [InverseProperty(nameof(PersonType.Person))]
        public virtual PersonType PersonCodeNavigation { get; set; }
    }
}