// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AugustCodingExercise
{
    public partial class PersonType
    {
        public PersonType()
        {
            Person = new HashSet<Person>();
        }

        [Key]
        [StringLength(10)]
        public string PersonCode { get; set; }
        [StringLength(250)]
        public string TypeDescription { get; set; }

        [InverseProperty("PersonCodeNavigation")]
        public virtual ICollection<Person> Person { get; set; }
    }
}